version: "2"

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - dogsled
    - durationcheck
    - dupword
    - errcheck
    - copyloopvar
    - errchkjson
    - goconst
    - sloglint
    - goheader
    - gosec
    - gocritic
    - govet
    - ginkgolinter
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nosprintfhostport
    - nilerr
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - testifylint
    - tparallel
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    - wrapcheck
    - sqlclosecheck
    - promlinter
    - prealloc
    - contextcheck
  settings:
    gocritic:
      disabled-checks: [captLocal]
    revive:
      rules:
        - name: blank-imports
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
