with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceNameSnake}}.go"

packages:
  # tron API package
  github.com/kilnfi/tron-validator-watcher/internal/tron:
    interfaces:
      NetworkClient:
      AccountClient:
