// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	tron "github.com/kilnfi/tron-validator-watcher/internal/tron"
	mock "github.com/stretchr/testify/mock"
)

// AccountClient is an autogenerated mock type for the AccountClient type
type AccountClient struct {
	mock.Mock
}

type AccountClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountClient) EXPECT() *AccountClient_Expecter {
	return &AccountClient_Expecter{mock: &_m.Mock}
}

// GetAccount provides a mock function with given fields: address
func (_m *AccountClient) GetAccount(address string) (*tron.Account, error) {
	ret := _m.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *tron.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*tron.Account, error)); ok {
		return rf(address)
	}
	if rf, ok := ret.Get(0).(func(string) *tron.Account); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tron.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountClient_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type AccountClient_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - address string
func (_e *AccountClient_Expecter) GetAccount(address interface{}) *AccountClient_GetAccount_Call {
	return &AccountClient_GetAccount_Call{Call: _e.mock.On("GetAccount", address)}
}

func (_c *AccountClient_GetAccount_Call) Run(run func(address string)) *AccountClient_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AccountClient_GetAccount_Call) Return(_a0 *tron.Account, _a1 error) *AccountClient_GetAccount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountClient_GetAccount_Call) RunAndReturn(run func(string) (*tron.Account, error)) *AccountClient_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetWitnesses provides a mock function with given fields: address
func (_m *AccountClient) GetWitnesses(address string) (*tron.Witness, error) {
	ret := _m.Called(address)

	if len(ret) == 0 {
		panic("no return value specified for GetWitnesses")
	}

	var r0 *tron.Witness
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*tron.Witness, error)); ok {
		return rf(address)
	}
	if rf, ok := ret.Get(0).(func(string) *tron.Witness); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tron.Witness)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountClient_GetWitnesses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWitnesses'
type AccountClient_GetWitnesses_Call struct {
	*mock.Call
}

// GetWitnesses is a helper method to define mock.On call
//   - address string
func (_e *AccountClient_Expecter) GetWitnesses(address interface{}) *AccountClient_GetWitnesses_Call {
	return &AccountClient_GetWitnesses_Call{Call: _e.mock.On("GetWitnesses", address)}
}

func (_c *AccountClient_GetWitnesses_Call) Run(run func(address string)) *AccountClient_GetWitnesses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AccountClient_GetWitnesses_Call) Return(_a0 *tron.Witness, _a1 error) *AccountClient_GetWitnesses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountClient_GetWitnesses_Call) RunAndReturn(run func(string) (*tron.Witness, error)) *AccountClient_GetWitnesses_Call {
	_c.Call.Return(run)
	return _c
}

// ListWitnesses provides a mock function with no fields
func (_m *AccountClient) ListWitnesses() (*tron.Witnesses, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListWitnesses")
	}

	var r0 *tron.Witnesses
	var r1 error
	if rf, ok := ret.Get(0).(func() (*tron.Witnesses, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *tron.Witnesses); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tron.Witnesses)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountClient_ListWitnesses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWitnesses'
type AccountClient_ListWitnesses_Call struct {
	*mock.Call
}

// ListWitnesses is a helper method to define mock.On call
func (_e *AccountClient_Expecter) ListWitnesses() *AccountClient_ListWitnesses_Call {
	return &AccountClient_ListWitnesses_Call{Call: _e.mock.On("ListWitnesses")}
}

func (_c *AccountClient_ListWitnesses_Call) Run(run func()) *AccountClient_ListWitnesses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AccountClient_ListWitnesses_Call) Return(_a0 *tron.Witnesses, _a1 error) *AccountClient_ListWitnesses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountClient_ListWitnesses_Call) RunAndReturn(run func() (*tron.Witnesses, error)) *AccountClient_ListWitnesses_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountClient creates a new instance of AccountClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountClient {
	mock := &AccountClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
