// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	tron "github.com/kilnfi/tron-validator-watcher/internal/tron"
	mock "github.com/stretchr/testify/mock"
)

// NetworkClient is an autogenerated mock type for the NetworkClient type
type NetworkClient struct {
	mock.Mock
}

type NetworkClient_Expecter struct {
	mock *mock.Mock
}

func (_m *NetworkClient) EXPECT() *NetworkClient_Expecter {
	return &NetworkClient_Expecter{mock: &_m.Mock}
}

// GetBlockByNumber provides a mock function with given fields: ctx, number
func (_m *NetworkClient) GetBlockByNumber(ctx context.Context, number int64) (*tron.Block, error) {
	ret := _m.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockByNumber")
	}

	var r0 *tron.Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*tron.Block, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *tron.Block); ok {
		r0 = rf(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tron.Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetworkClient_GetBlockByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockByNumber'
type NetworkClient_GetBlockByNumber_Call struct {
	*mock.Call
}

// GetBlockByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number int64
func (_e *NetworkClient_Expecter) GetBlockByNumber(ctx interface{}, number interface{}) *NetworkClient_GetBlockByNumber_Call {
	return &NetworkClient_GetBlockByNumber_Call{Call: _e.mock.On("GetBlockByNumber", ctx, number)}
}

func (_c *NetworkClient_GetBlockByNumber_Call) Run(run func(ctx context.Context, number int64)) *NetworkClient_GetBlockByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *NetworkClient_GetBlockByNumber_Call) Return(_a0 *tron.Block, _a1 error) *NetworkClient_GetBlockByNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NetworkClient_GetBlockByNumber_Call) RunAndReturn(run func(context.Context, int64) (*tron.Block, error)) *NetworkClient_GetBlockByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestBlock provides a mock function with given fields: ctx
func (_m *NetworkClient) GetLatestBlock(ctx context.Context) (*tron.Block, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestBlock")
	}

	var r0 *tron.Block
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*tron.Block, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *tron.Block); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tron.Block)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NetworkClient_GetLatestBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestBlock'
type NetworkClient_GetLatestBlock_Call struct {
	*mock.Call
}

// GetLatestBlock is a helper method to define mock.On call
//   - ctx context.Context
func (_e *NetworkClient_Expecter) GetLatestBlock(ctx interface{}) *NetworkClient_GetLatestBlock_Call {
	return &NetworkClient_GetLatestBlock_Call{Call: _e.mock.On("GetLatestBlock", ctx)}
}

func (_c *NetworkClient_GetLatestBlock_Call) Run(run func(ctx context.Context)) *NetworkClient_GetLatestBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *NetworkClient_GetLatestBlock_Call) Return(_a0 *tron.Block, _a1 error) *NetworkClient_GetLatestBlock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NetworkClient_GetLatestBlock_Call) RunAndReturn(run func(context.Context) (*tron.Block, error)) *NetworkClient_GetLatestBlock_Call {
	_c.Call.Return(run)
	return _c
}

// NewNetworkClient creates a new instance of NetworkClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNetworkClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *NetworkClient {
	mock := &NetworkClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
