name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  image-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.determine-tag.outputs.tag }}
    steps:
    - name: Determine Image Tag
      id: determine-tag
      run: |
        if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "Setting image tag to ${{ github.ref_name }}"
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        else
            TAG="${{ github.ref_name }}-$(echo ${{ github.sha }} | cut -c1-7)"
            echo "Setting image tag to $TAG"
            echo "tag=$TAG" >> $GITHUB_OUTPUT
        fi

  build-image:
    needs:
      - image-tag
    uses: kilnfi/nakamoto/.github/workflows/docker-build-and-push.ci.yml@main
    with:
      dockerfile: Dockerfile
      tags: tron-validator-watcher:${{ needs.image-tag.outputs.tag }}
      platforms: linux/amd64,linux/arm64
      runner: fixed-egress-16c-64g
      manage_ecr_repository: false
