name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  id-token: write

env:
  BINARY_NAME: tron-validator-watcher

jobs:
  binaries:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        arch:
          - amd64
          - arm64
    runs-on: ${{ matrix.os }}
    env:
      ARCH_NAME: ${{ matrix.arch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Export Variables
        id: export-variables
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            echo "os_name=linux" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            echo "os_name=darwin" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: |
          if [ "$OS_NAME" == "linux" ]; then
            sudo apt-get update
            if [ "${{ matrix.arch }}" == "amd64" ]; then
              sudo apt-get install -y build-essential
            elif [ "${{ matrix.arch }}" == "arm64" ]; then
              sudo apt install -y build-essential gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
            fi
          elif [ "$OS_NAME" == "darwin" ]; then
            brew update
            brew install sqlite
          fi
        env:
          OS_NAME: ${{ steps.export-variables.outputs.os_name }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26

      - name: Build ${{matrix.os}}-${{matrix.arch}} binary
        id: build
        run: |
          OUTPUT_NAME="${{ env.BINARY_NAME }}_${{ github.ref_name }}_${OS_NAME}_${ARCH_NAME}"
          OUTPUT_DIR=dist/${OUTPUT_NAME}
          ARCHIVE_NAME="${OUTPUT_NAME}.tar.gz"

          # debug
          echo "OUTPUT_NAME=${OUTPUT_NAME}"
          echo "DIR=${OUTPUT_DIR}"
          echo "ARCH=${ARCH_NAME}"
          echo "ARCH2=${{ env.ARCH_NAME}}"

          echo "output_dir=${OUTPUT_DIR}" >> $GITHUB_OUTPUT
          mkdir -p ${OUTPUT_DIR}

          if [ "${OS_NAME}" = "linux" ] && [ "${ARCH_NAME}" = "arm64" ]; then
            export CC=aarch64-linux-gnu-gcc
            export CXX=aarch64-linux-gnu-g++
          fi

          CGO_ENABLED=1 GOOS=$OS_NAME GOARCH=$ARCH_NAME \
          go build -ldflags="-s -w" -o ${OUTPUT_DIR}/${{ env.BINARY_NAME }} cmd/watcher/main.go
          tar -czvf ${OUTPUT_DIR}/${ARCHIVE_NAME} -C ${OUTPUT_DIR} ${{ env.BINARY_NAME }}
        env:
          OS_NAME: ${{ steps.export-variables.outputs.os_name }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "${{ env.DIRECTORY }}/*.tar.gz"
          tag: ${{ github.ref_name }}
          file_glob: true
        env:
          DIRECTORY: ${{ steps.build.outputs.output_dir }}

  image-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.determine-tag.outputs.tag }}
    steps:
    - name: Determine Image Tag
      id: determine-tag
      run: |
        if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "Setting image tag to ${{ github.ref_name }}"
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        else
            TAG="${{ github.ref_name }}-$(echo ${{ github.sha }} | cut -c1-7)"
            echo "Setting image tag to $TAG"
            echo "tag=$TAG" >> $GITHUB_OUTPUT
        fi

  build-image:
    needs:
      - image-tag
    uses: kilnfi/nakamoto/.github/workflows/docker-build-and-push.ci.yml@main
    with:
      dockerfile: Dockerfile
      tags: tron-validator-watcher:${{ needs.image-tag.outputs.tag }}
      platforms: linux/amd64,linux/arm64
      runner: fixed-egress-16c-64g
      manage_ecr_repository: false
